ATravelersGuideToSerdan/Pages/Character/NPCIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.Character
{
    public class NPCIndexModel : PageModel
    {
        private ISerdan _Db;

        public NPCIndexModel(ISerdan Db)
        {
            _Db = Db;
        }

        public void OnGet()
        {

        }
        public IActionResult OnPostSelectedRace(string race)
        {
            if (race == null)
            {
                return Page();
            }
            else
            {
                List<Models.NPC> NpcOfARace = new List<Models.NPC>();

                NpcOfARace = _Db.GetMultipleNPCs(race);
                List<ViewModels.NpcListViewModel> compactNpcList = new List<ViewModels.NpcListViewModel>();
                foreach (var npc in NpcOfARace)
                {

                }
                return RedirectToPage("GetNpcList", NpcOfARace);
            }
        }

        //public List<Models.NPC> PageResult GetCharacters(string race)
        //{
        //    List<Models.NPC> NpcOfARace = _Db.GetMultipleNPCs(race);

        //    return Page()
        //}

    }
}

ATravelersGuideToSerdan/Pages/NPC/GetNpcList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPC
{
    public class GetNpcListModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ATravelersGuideToSerdan/Pages/NPC/NPCIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPC
{
    public class NPCIndexModel : PageModel
    {
        private ISerdan _Db;

        public NPCIndexModel(ISerdan Db)
        {
            _Db = Db;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPostSelectedRace(string race)
        {
            if (race == null)
            {
                return Page();
            }
            else
            {
                List<Models.NPC> NpcOfARace = new List<Models.NPC>();

                NpcOfARace = _Db.GetMultipleNPCs(race);
                List<ViewModels.NpcListViewModel> compactNpcList = new List<ViewModels.NpcListViewModel>();
                foreach (var npc in NpcOfARace)
                {

                }
                return RedirectToPage("GetNpcList", NpcOfARace);
            }
        }


        //public List<Models.NPC> PageResult GetCharacters(string race)
        //{
        //    List<Models.NPC> NpcOfARace = _Db.GetMultipleNPCs(race);
        //    return Page()
        //}
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep1.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Models;
using ATravelersGuideToSerdan.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class CreateNPCstep1Model : PageModel
    {
        private IMapper _mapper;
        private ISerdan _Db;

        public CreateNPCstep1Model(IMapper mapper, ISerdan Db)
        {
            _mapper = mapper;
            _Db = Db;
        }

        //[BindProperty]
        public NPC NpcToAdd { get; set; }
        [TempData]
        public string MessageToUser { get; set; }

        public int NPCId { get; set; }



        public void OnGet()
        {

        }

        //public async Task<IActionResult> OnPostAsync()
        //public IActionResult OnPost()
        public IActionResult OnPost(NPC NpcToAdd)
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}
            //convert data from CreateNPCstep1 to NPCgeneralviewmodel
            //Save to database part1 of the data
            //try
            //{
            //    // _mapper.Map(NpcToAdd, npcToAddToDb);
            //    npcToAdd = _Db.AddNPC(npcToAdd);
            //    //_mapper.Map(npcToAddToDb, NpcToAdd);
            //}
            //catch (Exception)
            //{
                MessageToUser = "Ops, something happend!! Either was your data not convertible or not savable.";
            //    return Page();
            //}
            //NPCId = NpcToAdd.NpcId;
            //return RedirectToPage("CreateNPCstep2",nPCId);
            return RedirectToPage("CreateNPCstep2");
        }
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep2.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Models;
using ATravelersGuideToSerdan.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class CreateNPCstep2Model : PageModel
    {
        private IMapper _mapper;
        private ISerdan _Db;

        public CreateNPCstep2Model(IMapper mapper, ISerdan Db)
        {
            _mapper = mapper;
            _Db = Db;
        }

        [BindProperty]
        public NpcStat NpcToAdd { get; set; }
        [TempData]
        public string MessageToUser { get; set; }

        public int NPCId { get; set; }


        
        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {

            return RedirectToPage("CreateNPCstep3");
        }

        public IActionResult OnBack()
        {
            return RedirectToPage("CreateNPCstep1");
        }
        
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep3.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Models;
using ATravelersGuideToSerdan.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class CreateNPCstep3Model : PageModel
    {
        private IMapper _mapper;
        private ISerdan _Db;

        public CreateNPCstep3Model(IMapper mapper, ISerdan Db)
        {
            _mapper = mapper;
            _Db = Db;
        }

        [BindProperty]
        public NpcPower npcToAdd { get; set; }
        [TempData]
        public string messageToUser { get; set; }

        public int nPCId { get; set; }

       

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            return RedirectToPage("CreateNPCstep4");
        }

        public IActionResult OnBack()
        {
            return RedirectToPage("CreateNPCstep2");
        }
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep4.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Models;
using ATravelersGuideToSerdan.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class CreateNPCstep4Model : PageModel
    {
        private IMapper _mapper;
        private ISerdan _Db;

        public CreateNPCstep4Model(IMapper mapper, ISerdan Db)
        {
            _mapper = mapper;
            _Db = Db;
        }

        [BindProperty]
        public NpcMagic NpcToAdd { get; set; }
        [TempData]
        public string MessageToUser { get; set; }

        public int NPCId { get; set; }

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            return RedirectToPage("");

        }
        public IActionResult OnBack()
        {
            return RedirectToPage("CreateNPCstep3");
        }
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/GetNpcList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class GetNpcListModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/NPCIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ATravelersGuideToSerdan.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ATravelersGuideToSerdan.Pages.NPCPage
{
    public class NPCIndexModel : PageModel
    {
        private ISerdan _Db;

        public NPCIndexModel(ISerdan Db)
        {
            _Db = Db;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPostSelectedRace(string race)
        {
            if (race == null)
            {
                return Page();
            }
            else
            {
                List<Models.NPC> NpcOfARace = new List<Models.NPC>();

                NpcOfARace = _Db.GetMultipleNPCs(race);
                List<ViewModels.NpcListViewModel> compactNpcList = new List<ViewModels.NpcListViewModel>();
                foreach (var npc in NpcOfARace)
                {

                }
                return RedirectToPage("GetNpcList", NpcOfARace);
            }
        }


        //public List<Models.NPC> PageResult GetCharacters(string race)
        //{
        //    List<Models.NPC> NpcOfARace = _Db.GetMultipleNPCs(race);
        //    return Page()
        //}
    }
}

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep1.cshtml
@page
@namespace ATravelersGuideToSerdan.Pages.NPCPage
@model ATravelersGuideToSerdan.Models.NPC

<h1>Skapa/lägg till en ny Npc.</h1>
<div>Denna guide skapar/lägger till en ny Npc till En resandes guide till Serdan. Guiden har 4 steg, steg 1 är generel info, steg 2 är grundegenskaper, steg 3 är krafter och steg 4 är magi.</div>
@*<h1>Create/add a new NPC.</h1>
    <div>This creates/adds a new Npc to the Travelers Guide To Serdan. This is a wizard of 4 steps. Step 1 is general data. Step 2 is Npc stats. Step 3 is about Powers</div>*@
@*@if (MessageToUser != "")
    {

    }*@
<hr />
<form method="post">
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcName"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcName" />
        <span asp-validation-for="NpcName"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcEvenKnownAs"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcEvenKnownAs" />
        <span asp-validation-for="NpcEvenKnownAs"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcAlias"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcAlias" />
        <span asp-validation-for="NpcAlias"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcDescriptivePhrase"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcDescriptivePhrase" />
        <span asp-validation-for="NpcDescriptivePhrase"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcLooks"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcLooks" />
        <span asp-validation-for="NpcLooks"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcDescription"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcDescription" />
        <span asp-validation-for="NpcDescription"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcCurrentResidence"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcCurrentResidence" />
        <span asp-validation-for="NpcCurrentResidence"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRace"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj ras</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcRace" />
        <span asp-validation-for="NpcRace"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcFamily"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcFamily" />
        <span asp-validation-for="NpcFamily"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcArchetyp"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Urtyp</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcArchetyp" />
        <span asp-validation-for="NpcArchetyp"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcKilledBy"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj person</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcKilledBy" />
        <span asp-validation-for="NpcKilledBy"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcBehaviour"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcBehaviour" />
        <span asp-validation-for="NpcBehaviour"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcAsAParent"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcAsAParent" />
        <span asp-validation-for="NpcAsAParent"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcGoal"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcGoal" />
        <span asp-validation-for="NpcGoal"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcInBattle"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcInBattle" />
        <span asp-validation-for="NpcInBattle"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcsMother"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Moder</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcsMother" />
        <span asp-validation-for="NpcsMother"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcsFather"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Fader</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcsFather" />
        <span asp-validation-for="NpcsFather"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcsSerdanEdlosiChildren"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Barn</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcsSerdanEdlosiChildren" />
        <span asp-validation-for="NpcsSerdanEdlosiChildren"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcsRegularChildren"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Barn</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcsRegularChildren" />
        <span asp-validation-for="NpcsRegularChildren"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRegardingAets"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcRegardingAets" />
        <span asp-validation-for="NpcRegardingAets"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRegardingDemons"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcRegardingDemons" />
        <span asp-validation-for="NpcRegardingDemons"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRegardingDragons"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcRegardingDragons" />
        <span asp-validation-for="NpcRegardingDragons"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRegardingGrips"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcRegardingGrips" />
        <span asp-validation-for="NpcRegardingGrips"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRegardingOthers"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcRegardingOthers" />
        <span asp-validation-for="NpcRegardingOthers"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcFriends"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Vän</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcFriends" />
        <span asp-validation-for="NpcFriends"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcAllies"></label>
        <div class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2"><button class="btn btn-sm btn-dark">Välj Allierad</button></div>
        <input class="col-md-8 col-8 col-xl-8 col-lg-8 col-sm-8" asp-for="NpcAllies" />
        <span asp-validation-for="NpcAllies"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcRivals"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Rival</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcRivals" />
        <span asp-validation-for="NpcRivals"></span>
    </div>

    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcEnemies"></label>
        <div class="col-md-1 col-1 col-xl-1 col-lg-1 col-sm-1"><button class="btn btn-sm btn-dark">Välj Fiende</button></div>
        <input class="col-md-9 col-9 col-xl-9 col-lg-9 col-sm-9" asp-for="NpcEnemies" />
        <span asp-validation-for="NpcEnemies"></span>
    </div>

    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcOtherResideces"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcOtherResideces" />
        <span asp-validation-for="NpcOtherResideces"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcInTheHistory"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcInTheHistory" />
        <span asp-validation-for="NpcInTheHistory"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcSecrets"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcSecrets" />
        <span asp-validation-for="NpcSecrets"></span>
    </div>
    <div class="form-group row">
        <label class="col-md-2 col-2 col-xl-2 col-lg-2 col-sm-2" asp-for="NpcAssets"></label>
        <input class="col-md-10 col-10 col-xl-10 col-lg-10 col-sm-2" asp-for="NpcAssets" />
        <span asp-validation-for="NpcAssets"></span>
    </div>
    @*<a asp-action="postAsync" class="btn btn-dark">Next</a>*@
    <button type="submit" class="btn btn-dark">Till steg 2</button>
</form>

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep2.cshtml
@page
@namespace ATravelersGuideToSerdan.Pages.NPCPage
@model ATravelersGuideToSerdan.Models.NPC

<h1>Step 2 in Creating/Adding a NPC.</h1>


<form method="post">

    <button type="submit" class="btn btn-dark">Next</button>
</form>


<a asp-page="CreateNPCStep1" class="btn btn-dark">Back</a>

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep3.cshtml
@page
@model ATravelersGuideToSerdan.Models.NPC

<h1>step3</h1>

<form method="post">
<button type="submit" class="btn btn-dark">Next</button>
</form>

<a asp-page="CreateNPCStep2" class="btn btn-dark">Back</a>

ATravelersGuideToSerdan/Pages/NPCPage/CreateNPCstep4.cshtml
@page
@model ATravelersGuideToSerdan.Models.NPC

<h1>Step 4</h1>

<form method="post">
    <button type="submit" class="btn btn-dark">Next</button>
</form>

<a asp-page="CreateNPCStep3" class="btn btn-dark">Back</a>

ATravelersGuideToSerdan/Pages/NPCPage/GetNpcList.cshtml
@page
@*@model ATravelersGuideToSerdan.Pages.NPC.GetNpcListModel*@
@model List<ATravelersGuideToSerdan.ViewModels.NpcGeneralViewModel>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>@ViewBag.Title</h2>

<hr />

@if (Model != null)
{
    <ul>
        @foreach (var Npc in Model)
        {
            <li>
                @*@Html.Partial("_ANpc", Npc)*@

                <a asp-page="ANpc" asp-route-id="@Npc.NpcId">@Npc.NpcName</a>
            </li>
        }
    </ul>
}
else
{
        <span>No characters was loaded.</span>
}

ATravelersGuideToSerdan/Pages/NPCPage/NPCIndex.cshtml
@page
@model ATravelersGuideToSerdan.Pages.NPCPage.NPCIndexModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h2>NpcIndex</h2>
<div>
    <div>
        <form asp-page-handler="SelectedRace" method="Post" asp-route-race="serdan">
            <input type="submit" value="Serdan" class="btn btn-info" />
        </form>
    </div>
    <div>
        <form asp-page-handler="SelectedRace" method="Post" asp-route-race="drakar">
            <input type="submit" value="Drakar" class="btn btn-info" />
        </form>
    </div>
    <div>
        <form asp-page-handler="SelectedRace" method="Post" asp-route-race="edlosi">
            <input type="submit" value="Edlosi" class="btn btn-danger" />
        </form>
    </div>
    <div>
        <form asp-page-handler="SelectedRace" method="Post" asp-route-race="gripar">
            <input type="submit" value="Gripar" class="btn btn-danger" />
        </form>
    </div>
    <div>
        <form asp-page-handler="SelectedRace" method="Post" asp-route-race="människor">
            <input type="submit" value="Människor" class="btn btn-success" />
        </form>
    </div>
    <div>
         <a asp-page="CreateNPCstep1" class="btn btn-dark" >Create/Add a character</a>
    </div>
</div>

@*asp-page = action

    asp-page-handler="delete, put get post...

    asp-route-id


    <form asp-page-handler="post" asp-route-race="serdan">


        [BindProperty]

        <input asp-for="NPC.Name" />*@

ATravelersGuideToSerdan/Pages/NPCPage/_ANpc.cshtml
@model ATravelersGuideToSerdan.ViewModels.NpcGeneralViewModel

<li>
    @*@Ajax.ActionLink(Model.NpcName, "GetNpc", "NPC", new { Id = Model.NpcId },
    new AjaxOptions { UpdateTargetId="ContentBody", InsertionMode=InsertionMode.Replace})*@
</li>